/*
 * 2014+ Copyright (c) Evgeniy Polyakov <zbr@ioremap.net>
 * All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include "route.h"

using namespace ioremap;

extern "C" {

//This header is generated by cgo in compile time
#include "_cgo_export.h"

void session_get_routes(ell_session *session, context_t context)
{
	std::vector<dnet_route_entry> entries = session->get_routes();

	for (auto it = entries.begin(); it != entries.end(); ++it) {
		go_route_callback(&(*it), context);
	}
}

} // extern "C"
